Разметка всех страниц
htmlacademy-htmlcss/2181423-sedona-35 pull request #2
Opened 2022-10-05 15:35 UTC by yaremenkoms

---
:mortar_board: [Разметка всех страниц](https://up.htmlacademy.ru/htmlcss/35/user/2181423/tasks/5)

:boom: https://htmlacademy-htmlcss.github.io/2181423-sedona-35/2/

2022-10-05 17:00 UTC, andreysgra requested changes
В целом задание выполнено достаточно неплохо.

Если у вас возникнут вопросы, то мне лучше писать в телеграм (ссылка в моём профиле наставника). Можно писать и в ВК, но в телеграм оперативнее.

2022-10-05 17:00 UTC, andreysgra commented on index.html
> +      <img class="logo" src="" alt="Логотип Город Седона">
Как правило логотип сайта делают ссылкой на главную страницу. Особенно учитывая тот момент, что вы логотип поместили в основную навигацию сайта. То есть изображение нужно обернуть ссылкой.

2022-10-05 17:00 UTC, andreysgra commented on index.html
> +          <a class="navigation-link" href="main.html">Главная</a>
Главная страница - index.html, та которую вы разметили.

2022-10-05 17:00 UTC, andreysgra commented on index.html
> +            </span>
Текст этой ссылки присутствует в макете в явном виде, так что его не нужно оборачивать в `span` с классом `visually-hidden`.

2022-10-05 17:00 UTC, andreysgra commented on index.html
> +          </li></ul>
Есть у нас критерий [PROJ-01](https://up.htmlacademy.ru/htmlcss/35/criteries#PROJ-01) про кодгайд. Стоит обратить внимание на форматирование кода https://codeguide.academy/html-css.html#formatting (пример в правой колонке).

Пишу замечание только здесь, но в целом форматирование нужно поправить по всему коду.

2022-10-05 17:00 UTC, andreysgra commented on index.html
> +</section>
Не очень удачная разметка этой части макета.
![image](https://user-images.githubusercontent.com/17790771/194116651-e60679a4-6bb9-45d0-b36b-56f4d27b3e45.png)

Недостатки:
1. Пять секций. Секция - это более-менее крупный смысловой блок сайта и вполне самодостаточный. Здесь же мы видим некую общность - идёт перечисление преимуществ городка. А если идёт перечисление, то это список, в данном случае `ul`. Список из пяти `li` - по количеству преимуществ.
2. Внутри каждой секции вы использовали список из одного элемента, но особого смысла в списке из одного элемента нет. Список не нужен.
3. Так как вместо секций будет список, то скрытый заголовок "Преимущества" не нужен.

2022-10-05 17:00 UTC, andreysgra commented on index.html
> +  </section>
Здесь тоже вместо секций лучше использовать список из трёх элементов:
![image](https://user-images.githubusercontent.com/17790771/194117584-b496bf91-1601-44f3-953e-d8e11140781d.png)

Ошибки такие же, что и в предыдущем блоке преимуществ.

2022-10-05 17:00 UTC, andreysgra commented on index.html
> +      <img class="icon-house" src="" alt="Дом иконка">
Эти изображения декоративные (добавляются через CSS), а значит для них не нужно использовать тег `img`.
![image](https://user-images.githubusercontent.com/17790771/194113880-63b0de32-60f3-4ff4-b3b0-d53d2e09c1d0.png)

2022-10-05 17:14 UTC, yaremenkoms commented
Большое спасибо за ваши рекомендации! Буду дорабатывать.

2022-10-06 13:27 UTC, yaremenkoms reviewed
Обернула логотип в ссылку. Назначила главной страницей index.html. Сделала списки вместо секций. Убрала img с декоративных иконок.

2022-10-06 16:28 UTC, andreysgra requested changes

2022-10-06 16:28 UTC, andreysgra commented on index.html
> +              <span>Хочу сюда</span>
В [этом комментарии ](https://github.com/htmlacademy-htmlcss/2181423-sedona-35/pull/2#discussion_r988133077) я писал, что тег `span` не нужен вовсе. В данном случае это лишний элемент разметки.

2022-10-06 16:28 UTC, andreysgra commented on index.html
> +    <img class="picture" src="" alt="Изображение Седоны с кустами на переднем фоне и флагами">
А вот здесь уже ошибка валидации HTML. Внутри списка (дочерние элементы) могут быть только теги `li`. Валидность HTML можно проверить [здесь](https://validator.w3.org/#validate_by_input).

Нужно тег `img` поместить внутрь `li`:
```
<li class="advantages-item">
  <h3 class="advantages-title">Настоящий городок</h3>
  <p class="advantages-description">Седона — не аттракцион для туристов, там течёт своя жизнь</p>
  <img class="picture" src="" alt="Изображение Седоны с кустами на переднем фоне и флагами">
</li>
```

2022-10-06 16:28 UTC, andreysgra commented on index.html
> +      <a href="http://htmlacademy.ru"><img class="logo" src="" alt="Логотип Город Седона"></a>
В прошлый раз забыл написать: в критерии [ALLY-01](https://up.htmlacademy.ru/htmlcss/35/criteries#ALLY-01) есть такое упоминание _Подпись в конце описания **должна** иметь точку_. Добавьте точку в конце текста во всех `alt`.

2022-10-06 16:28 UTC, andreysgra commented on index.html
> +    </li>
Здесь аналогичная ошибка. Должно быть так:
```
<li class="advantages-item">
  <h3 class="advantages-title">Там есть мост дьявола</h3>
  <p class="advantages-description">Да, по нему можно пройти! Если вы осмелитесь, разумеется</p>
  <img class="picture" src="" alt="Изображение Седоны с кустами на переднем фоне и флагами">
</li>
```

2022-10-06 16:28 UTC, andreysgra commented on index.html
> +      <span class="icon-house" src="" alt="Дом иконка">
1. Атрибуты `src` и `alt` могут быть только у тега `img`, а здесь тег `span`.
2. `span` здесь собственно не нужен, как и любой другой тег. Иконка будет добавляться через CSS, как фоновое изображение тега `<li class="advantages-item">`.

2022-10-10 18:26 UTC, yaremenkoms reviewed
Внесены правки 2

2022-10-11 15:53 UTC, andreysgra requested changes
К сожалению есть критические ошибки и на этот раз задание принять не могу. Ошибки нужно исправить.

2022-10-11 15:53 UTC, andreysgra commented on index.html
> +            </a>
Здесь ни `span`, ни `p` не нужен, так как это текст ссылки.
Просто `<a class="navigation-link" href="#">Хочу сюда</a>`.

2022-10-11 15:53 UTC, andreysgra commented on index.html
> +  < /li>
```suggestion
  </li>
```
То есть лишний пробел после символа `<`.

2022-10-11 15:53 UTC, andreysgra commented on index.html
> +    <img class="picture" src="" alt="Изображение Седоны с кустами на переднем фоне и флагами">
```suggestion
    <img class="picture" src="" alt="Изображение Седоны с кустами на переднем фоне и флагами.">
```
Нужна точка в конце описания.

2022-10-11 15:53 UTC, andreysgra commented on index.html
> +    <img class="picture" src="" alt="Изображение Седоны с кустами на переднем фоне и флагами">
```suggestion
    <img class="picture" src="" alt="Изображение Седоны с кустами на переднем фоне и флагами.">
```
Нужна точка в конце описания.

2022-10-11 15:53 UTC, andreysgra commented on index.html
> +      <span class="icon-suvenirs" src="" alt="Сувениры иконка">
[Здесь](https://github.com/htmlacademy-htmlcss/2181423-sedona-35/pull/2#discussion_r989258224) я писал замечание по первой иконке, но так как вторая и третья аналогичные иконки то по ни писать замечание не стал.

2022-10-12 08:11 UTC, andreysgra commented on index.html
> +      <a href="http://htmlacademy.ru"><img class="logo" src="/images/logo-sedona-header.svg" width="140" height="70" alt="Логотип Город Седон."></a>
```suggestion
      <a href="http://htmlacademy.ru"><img class="logo" src="images/logo-sedona-header.svg" width="140" height="70" alt="Логотип Город Седон."></a>
```
Так как это относительный путь. В данном случае от корня сайта. Поэтому путь не должен начинаться с символа `/`, иначе браузер не найдёт файл изображения. В этом можно убедиться, если посмотреть [опубликованную версию](https://htmlacademy-htmlcss.github.io/2181423-sedona-35/2/).

Здесь можно прочитать про [абсолютные и относительные пути](https://up.htmlacademy.ru/htmlcss/35/module/3/item/9).

2022-10-12 08:11 UTC, andreysgra commented on index.html
> +              <img class="icon-header" src="/images/search-icon-header.svg" width="20" height="20" alt="Иконка поиска">
1. Декоративное изображение. [Как отличить контентное изображение от декоративного](https://up.htmlacademy.ru/htmlcss/35/module/2/item/19). Удалите `img` из разметки. Иконка в дальнейшем будет добавлена средствами CSS (тег под неё не нужен).
2. Потерялся тег ссылки. Должно быть так: `<a class="navigation-link" href="#">`

2022-10-12 08:11 UTC, andreysgra commented on index.html
> +              <img class="icon-header" src="/images/heart-icon.svg" width="20" height="20" alt="Иконка нравится">
1. Декоративное изображение.
2. 2. Потерялся тег ссылки. Должно быть так: `<a class="navigation-link" href="#">`

2022-10-12 08:11 UTC, andreysgra commented on index.html
> +<img class="background" src="/images/background-main.jpg" width="1200" height="485" alt="Название Седона.">
background-main.jpg фоновое изображение, а фоновые изображения не добавляются в разметку. Удалите `img` для этой картинки.

2022-10-12 08:11 UTC, andreysgra commented on index.html
> +<img class="logo" src="/images/welcome.svg" width="458" height="352" alt="Добро пожаловать в раскошь. Седона. Потому что Большой Каньон рулит.">
```suggestion
<img class="logo" src="images/welcome.svg" width="458" height="352" alt="Добро пожаловать в раскошь. Седона. Потому что Большой Каньон рулит.">
```

2022-10-12 08:11 UTC, andreysgra commented on index.html
> +    <img class="picture" src="/images/photo-1.jpg" width="800" height="384" alt="Изображение Седоны с кустами на переднем фоне и флагами.">
```suggestion
    <img class="picture" src="images/photo-1.jpg" width="800" height="384" alt="Изображение Седоны с кустами на переднем фоне и флагами.">
```

2022-10-12 08:11 UTC, andreysgra commented on index.html
> +    <img class="picture" src="/images/photo-2.jpg" width="800" height="384" alt="Изображение Седоны с кустами на переднем фоне и флагами.">
```suggestion
    <img class="picture" src="images/photo-2.jpg" width="800" height="384" alt="Изображение Седоны с кустами на переднем фоне и флагами.">
```

2022-10-12 08:11 UTC, andreysgra commented on index.html
> +      <span class="icon-suvenirs" src="" alt="Сувениры иконка"></span>
Просто удалите `<span>`. Я это и просил сделать в предыдущие проверки :-). Во-первых, `span` не нужен, так как иконка будет добавляться средствами CSS к тегу `li`, а во-вторых, здесь ошибка синтаксиса HTML - у тега `span` не может быть атрибутов `src` и `alt`. Это атрибуты тега `img`.

2022-10-12 08:11 UTC, andreysgra commented on index.html
> +            <img src="/images/vk-icon.svg" width="24" height="14" alt="Логотип Вконтакте">
```suggestion
            <img src="images/vk-icon.svg" width="24" height="14" alt="Логотип Вконтакте">
```

2022-10-12 08:11 UTC, andreysgra commented on index.html
> +            <img src="/images/telegram-icon.svg" width="24" height="14" alt="Логотип Телеграм">
```suggestion
            <img src="images/telegram-icon.svg" width="24" height="14" alt="Логотип Телеграм">
```

2022-10-12 08:11 UTC, andreysgra commented on index.html
> +            <img src="/images/youtube-icon.svg" width="24" height="14" alt="Логотип Ютуба">
```suggestion
            <img src="images/youtube-icon.svg" width="24" height="14" alt="Логотип Ютуба">
```

2022-10-12 08:11 UTC, andreysgra commented on index.html
> +      <img src="/images/HTML-Academy-logo.svg" width="114.9" height="32.9" alt="Логотип HTML Academy">
```suggestion
      <img src="images/HTML-Academy-logo.svg" width="114.9" height="32.9" alt="Логотип HTML Academy.">
```

2022-10-12 08:11 UTC, merged

2022-10-12 15:45 UTC, yaremenkoms commented on index.html
> +<img class="logo" src="/images/welcome.svg" width="458" height="352" alt="Добро пожаловать в раскошь. Седона. Потому что Большой Каньон рулит.">
Не вижу вашего комментария полностю. Не понимаю, что здесь не так.

2022-10-12 15:46 UTC, yaremenkoms commented on index.html
> +    <img class="picture" src="/images/photo-1.jpg" width="800" height="384" alt="Изображение Седоны с кустами на переднем фоне и флагами.">
Аналогично с комментарием выше. Не вижу вашего комментария полностю. Не понимаю, что здесь не так.

2022-10-12 15:48 UTC, yaremenkoms commented on index.html
> +    <img class="picture" src="/images/photo-1.jpg" width="800" height="384" alt="Изображение Седоны с кустами на переднем фоне и флагами.">
Все, разобралась