CSS
htmlacademy-htmlcss/2181423-sedona-35 pull request #4
Opened 2022-10-30 12:47 UTC by yaremenkoms

2022-10-30 19:06 UTC, andreysgra requested changes

2022-10-30 19:06 UTC, andreysgra commented on index.html
> +<div class="main-index">
Почему-то вдруг `<main class="main-index"> `превратился в `<div class="main-index">`. Из-за этого ошибка валидации HTML:
![image](https://user-images.githubusercontent.com/17790771/198896298-ea85dc85-80bb-4f2d-bfbe-4730db7e5dfe.png)

2022-10-30 19:06 UTC, andreysgra commented on styles/styles.css
> +  background-image: url("../images/background-main.jpg");
По хорошему на `.main-index` (он же тег `main`) не стоит вешать фоновое изображение гор. Лучше сразу после `<h1 class="visually-hidden">Седона</h1>` добавить `div` в который переместить переместить `img` welcome.svg и на этот `div` наложить фон гор:

![image](https://user-images.githubusercontent.com/17790771/198896519-6ffe1ae0-9c07-4cf0-9209-ca53d2e6aba6.png)

2022-10-30 19:06 UTC, andreysgra commented on styles/styles.css
> +  src: url("../fonts/ptsans-400.woff2") format ("woff2")
```suggestion
  src: url("../fonts/ptsans-400.woff2") format("woff2")
```
Лишний пробел и в результате браузер шрифт не подключает.

2022-10-30 19:06 UTC, andreysgra commented on styles/styles.css
> +  src: url("../fonts/ptsans-700.woff2") format ("woff2");
```suggestion
  src: url("../fonts/ptsans-700.woff2") format("woff2");
```

2022-10-30 19:14 UTC, yaremenkoms reviewed
Исправила замечания

2022-11-01 08:38 UTC, merged

2022-11-04 20:57 UTC, yaremenkoms reviewed
Задание 5