Сетки страниц на флексах
htmlacademy-htmlcss/2181423-sedona-35 pull request #5
Opened 2022-11-04 20:59 UTC by yaremenkoms

2022-11-04 21:00 UTC, yaremenkoms reviewed
Задание выполнено

2022-11-05 18:40 UTC, andreysgra requested changes

2022-11-05 18:40 UTC, andreysgra commented on index.html
> +  <div class="page-container">
В этом проекте нет областей которые тянутся на всю ширину экрана и контентная область ограничена шириной 1200px. Поэтому данный контейнер `<div class="page-container">` нужно разместить не здесь, а сразу после тега `body`, обернув им всё содержимое страницы:
```
<div class="page-container">
  <header class="page-header"></header>

  <main class="main-container main-index"></main>

    <footer class="page-footer"></footer>
</div>
```

Тогда у вас будет общий контейнер центрирующий содержимое страницы.

2022-11-05 18:40 UTC, andreysgra commented on index.html
> +    <div class="page-footer-container">
Так как контейнер будет общим, то `<div class="page-footer-container">` внутри футера не нужен.

2022-11-05 18:40 UTC, andreysgra commented on styles/styles.css
> +  margin: 0 auto;
В соответствии с вышесказанным эти два свойства для `.navigation` не нужны.

2022-11-05 18:40 UTC, andreysgra commented on styles/styles.css
> +  flex-direction: column;
В демке барбершопа нет общего контейнера и эти два свойства, необходимые для создания sticky футера применены  к `body`. Вам же нужно будет перенести их в класс `page-container`, а также туда добавить свойство `min-height: 100%`.

На всякий случай [пример](https://codepen.io/angra/pen/jOWOXdp).

2022-11-05 18:40 UTC, andreysgra commented on styles/styles.css
> +  justify-content: space-between;
Что не нужно блоку `.advantages-list` так это `justify-content: space-between`. Чтобы расположить блоки согласно макета нужно кое-что сделать.
1. Добавить флекс-контейнеру `.advantages-list ` перенос строк (изменить значение свойства `flex-wrap`.
2. `li` с классом `advantages-item` не одинаковы. Те, что с картинками, тянутся на всю ширину `.advantages-list`. Поэтому нужно использовать разные классы. Тем, которые с картинками, задать класс `advantages-item-wide`. В этом классе определить как минимум 2 свойства: `width: 100%` и `display: flex`.
3. В элементах списка с классом `advantages-item-wide`, про которые я говорю в пункте 2, добавить дополнительные обёртки над контентом 
[здесь](https://user-images.githubusercontent.com/17790771/200135596-5e7a9590-0e5f-441e-a8d3-bbbd482c0ddc.png) и [здесь](https://user-images.githubusercontent.com/17790771/200135620-4cb7b407-4315-4d1b-a9cc-2a301904b975.png). Обёрткам задать ширину согласно макета: 400px и 800px соответственно.

Вот [пример](https://codepen.io/angra/pen/porbpae), но в нём разметка несколько отличается от вашей, но основная суть построения сетки такая. Однако советую посмотреть его тогда, когда вы попробуете самостоятельно создать сетку этого блока.

2022-11-05 18:40 UTC, andreysgra commented on styles/styles.css
> +}
Этот класс не нужен, а вот классу `page-footer` стоит задать `display: flex`.

2022-11-06 19:41 UTC, andreysgra requested changes

2022-11-06 19:41 UTC, andreysgra commented on index.html
>    </li>
Не совсем так, как должно быть.
1. Класс `advatages-item-wide` нужно применить к `li`, так как это общий контейнер для описания и фотографии.
2. `h3` и `p` нужно обернуть в `div`, без этого будет сложно. Зададим ему класс `advatages-item-wide-text`.
3. Изображение уже обёрнуто в `div`, но класс нужно заменить на другой, например `advatages-item-wide-image`.

В CSS в классе `advatages-item-wide-text` объявим свойство `width: 400px`, а в классе `advatages-item-wide-image` свойство `width: 800px`.

```
<li class="advantages-item-wide">
  <div class="advatages-item-wide-text">
     <h3 class="advantages-title_blue">Настоящий городок</h3>
     <p class="advantages-description_blue">Седона — не аттракцион для туристов, там течёт своя жизнь</p>
  </div>
  <div class="advatages-item-wide-image">
    <img class="picture" src="images/photo-1.jpg" width="800" height="384" alt="Изображение гор.">
  </div>
</li>
```

2022-11-06 19:41 UTC, andreysgra commented on index.html
> +    </div>
А здесь ошибка валидации HTML - вы `li` обернули в `div`. Этот блок нужно переделать по аналогии с первым.

2022-11-07 18:07 UTC, merged