Сетки компонентов на гридах
htmlacademy-htmlcss/2181423-sedona-35 pull request #7
Opened 2022-11-17 18:29 UTC by yaremenkoms

2022-11-17 18:31 UTC, yaremenkoms reviewed
Добавила page-footer grid-column: 1 / -1

2022-11-19 06:46 UTC, andreysgra requested changes

2022-11-19 06:46 UTC, andreysgra commented on styles/styles.css
> +  display: grid;
Здесь мы видим, что в строке 280 переопределяется значение свойства `display`:

![image](https://user-images.githubusercontent.com/17790771/202837788-d571a7b6-dc72-419a-a5e5-3fe45dcf14b0.png)

Соответственно раскладка элементов `.page-footer` производится с помощью `flex`. Значит то, что написано в строках 279 - 282 нужно удалить.

2022-11-19 06:46 UTC, andreysgra commented on styles/styles.css
> +  grid-template-columns: 150px 400px 120px;
Шаблон для колонок определён неверно. В данный момент раскладка элементов держится за счёт `flex`, но если его убрать, то сетка будет выглядеть вот так:
![image](https://user-images.githubusercontent.com/17790771/202837857-4fb0606c-c551-444a-bbe1-87a902351872.png)

Почему так произошло? На это есть несколько причин.
1. Ширина `.page-footer` равна 1200px. Считаем ширину шаблона: 150 + 400 + 120 = 670px.
2. Элементы наезжают друг на друга. Первой идёт секция `footer-media`, её ширина равна 145px и вроде бы она должна вмещаться в первую колонку, ширина которой 150px, но у секции есть `margin-left: 70px` и `margin-right: 250px`. Отступ слева + ширина секции = 215px, а вторая колонка должна начинаться после 150px, поэтому секция `page-footer-phone` наехала на секцию `footer-media`. Убираем отступы у `footer-media`, всё становится хорошо. У секции `page-footer-phone` также есть ненужный `margin-right`, убираем и его. Осталась секция `page-footer-logo` у которой тоже убираем `margin-right`.
3. Теперь нужно поработать над свойствами `.page-footer`. Добавим ему `padding-left: 70px; padding-right: 70px`. Это внутренние отступы, вместо убранных ранее внешних отступов у `footer-media` и `page-footer-logo`. Изменяем шаблон `grid-template-columns`. Предположим, что первая и третья колонки имеют одинаковую ширину 150px, а вторая колонка будет занимать всю доступную ширину. В результате шаблон будет иметь такой вид: `grid-template-columns: 150px 1fr 150px`.

2022-11-19 06:46 UTC, andreysgra commented on styles/styles.css
> +  grid-column: 1 / -1;
Это свойство не grid-контейнера, а grid-элемента и никакой пользы для `.page-footer` от него нет.

2022-11-19 06:46 UTC, andreysgra commented on styles/styles.css
> +  width: 350px;
Это свойство стоит удалить, так как вторая колонка должна занимать всю доступную ширину контейнера.

2022-11-20 14:32 UTC, merged